CREATE TABLE orders (
	id_order INTEGER PRIMARY KEY AUTOINCREMENT,
	date TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT CURRENT_DATE,
	date_creation TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE product (
	id_product INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) UNIQUE NOT NULL,
	price FLOAT NOT NULL
);
