CREATE TABLE orders (
	id_order INTEGER PRIMARY KEY AUTOINCREMENT,
	vat FLOAT NOT NULL DEFAULT 0,
	status VARCHAR(10) NOT NULL,
	cancel_reason TEXT,
	date TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT CURRENT_DATE,
	date_creation TIMESTAMP WITH TIMEZONE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE product (
	id_product INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) UNIQUE NOT NULL,
	price FLOAT NOT NULL
);

CREATE TABLE line_item (
	id_line_item INTEGER PRIMARY KEY AUTOINCREMENT,
	id_order INTEGER REFERENCES orders(id_order) NOT NULL,
	id_product INTEGER REFERENCES product(id_product) NOT NULL,
	quantity INTEGER NOT NULL,
	UNIQUE (id_order, id_product)
);
